### ISSUE TITLE
Inventory Consumption -- Add Inventory balance

### ISSUE THREAD

**Issue by KAMogler** [farm-entry/app#305]
ItemConsumption Endpoint has been updated to include current inventory balance by Item / Location.   When a user chooses their "Source Location" and then is selecting Inventory -- show current inventory balance by inventory item on the drop down selection.  
Current "display" is:
No. - Description - Base Unit of Measure.

The drop down selection list should "filter" to only include items at the "Source Location" from the ItemConsumption Endpoint. 

Would like the display to be two lines:   
No. - Description -  
**Inventory XXX** - Base Unit of Measure .
Example:
101 - Acepromazine 50 ml - 
     Inventory  -10 BTL

If the inventory balance is below zero, can we show balance  i.e -10  in red?    Note: I happened to select an item that has a negative inventory balance.

**Comment by mwoelfel13** [comment]
Completed with PR #313
