### ISSUE TITLE
Move Events - Get a "better" price for Positive Adjust entry

### ISSUE THREAD

**Issue by KAMogler** [farm-entry/app#311]
When moving pigs from on location (group) to another, we need to transfer the same pig cost from the sending location to the new receiving location.  I set up a new query endpoint InventoryByLocation.  I am filtering on 01 (Pigs) and trying to filter on MonthDate => today but it appears NAV converts Today to a static date (time of entry).  May want to add date filter in the APP call.

**Comment by mwoelfel13** [comment]
any update on the above question about math to calculate the price?

**Comment by KAMogler** [comment]
The price and unit of measure on Pigs should be Price / head, not price per pound.

**Comment by mwoelfel13** [comment]
If there is no price on the standard item journal THEN use the user input.

**Comment by KAMogler** [comment]
Correct.   And we will NOT show the price on the APP page.  This is just a "background" calculation to have a "determined price" on the Item Journals for Move Entries when posted into NAV.

**Comment by KAMogler** [comment]
For "testing" you can use Mkt Pigs as they will have "no cost" in standard journal and should use calculation.  If you use TN70  Gilts to Sows (GMA) or Cull Sows / GMA Gilts to Offsite, they both should have unit prices in the Standard journals.
