### ISSUE TITLE
Critical User frustration -- Event Date - 

### ISSUE THREAD

**Issue by KAMogler** [farm-entry/app#333]
The Event date (pull up calendar for input) doesn't work on my Apple phone if the web-services has been "dormant" for some time.  When I tried to enter an event this morning, the field populated with "today's date" and then became "non-responsive".  IE I couldn't get a calendar to pop up or change the date.   If I power cycled my phone (reset everything), I can come into the APP and the calendar works fine.   
Either we need the "APP refresh" process to be implemented quickly or we need to get this issue resolved ASAP.    The "old method" which "populated" today's date for every transaction, the calendar function was always responsive.

I don't know how it works on Android.

**Comment by KAMogler** [comment]
I had same issue today on Inventory Consumption.  The challenge is you can't "change" the date; it's "locked in to today".    This will be huge user frustration.

**Comment by mmogler** [comment]
We will try to resolve this with the user sessions issue
