### ISSUE TITLE
New "autoimport" transactions

### ISSUE THREAD

**Issue by KAMogler** [farm-entry/app#334]
GeneralJournal_
PurchaseHeader_
PurchaseLine_

A new Web service endpoint created for each and would like to use same structure as ItemJournal_   Attached are three "sample" files,
[PurchaseLine_053122_1804.csv](https://github.com/farm-entry/app/files/8809896/PurchaseLine_053122_1804.csv)
[PurchaseHeader_053122_1759.csv](https://github.com/farm-entry/app/files/8809897/PurchaseHeader_053122_1759.csv)
[GeneralJournal_053122_1758.csv](https://github.com/farm-entry/app/files/8809898/GeneralJournal_053122_1758.csv)

**Comment by mmogler** [comment]
Refactor the lambda to remove the logic from the vars.py. User will pass in the field type as part of the headers field.

ex from vars.py: 
`
date_fields = [
    'Posting_Date',
    'Document_Date',
]
`
becomes in the CSV Header
`d$Posting_Date` `d$Document_Date`


`
integer_fields = [
    'Line_No'
]
`
becomes in the CSV Header
`i$Line_No`



`
string_fields = [
    'Journal_Batch_Name'
]
`
becomes in the CSV Header
`s$Journal_Batch_Name`
