### ISSUE TITLE
Hotfix - Add User filters to JobCard query

### ISSUE THREAD

**Issue by mwoelfel13** [farm-entry/app#349]
The same filters applied to Jobs query need to be applied to JobCard query on table-edit feature

**Comment by KAMogler** [comment]
Also added a new JobTableUpdate endpoint.  This is a Job table query to limit fields to only those available to "edit" and also filters out Status:Completed.    This may help with the latency we are currently experiencing.

**Comment by mwoelfel13** [comment]
This was closed out with the last PR
